<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ACW-Lap-031" failures="1" tests="13" name="Users" time="0.423" errors="0" timestamp="2024-03-26T01:05:14 IST">
  <testcase classname="testng.com.Day1" name="print" time="0.034"/>
  <testcase classname="testng.com.Day1" name="print1" time="0.002"/>
  <testcase classname="testng.com.Day_2" name="mobilelogin" time="0.004"/>
  <testcase classname="testng.com.Day_2" name="mobilelogin2" time="0.009"/>
  <testcase classname="testng.com.Day_2" name="weblogin" time="0.002"/>
  <testcase classname="testng.com.Day3" name="deleteUser" time="0.003"/>
  <testcase classname="testng.com.Day3" name="viewUser" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testng.com.Day3.viewUser(Day3.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- viewUser -->
  <testcase classname="testng.com.Day4" name="addHotel" time="0.003"/>
  <testcase classname="testng.com.Day4" name="deletehotel" time="0.002"/>
  <testcase classname="testng.com.Day4" name="editHotel" time="0.002"/>
  <testcase classname="testng.com.Day4" name="viewHotel" time="0.002"/>
  <testcase classname="testng.com.Day3" name="addUser" time="0.002"/>
  <testcase classname="testng.com.Day3" name="edituser" time="0.0">
    <skipped/>
  </testcase> <!-- edituser -->
  <testcase classname="testng.com.Day_2" name="enabledmethod" time="0.0">
    <ignored/>
  </testcase> <!-- enabledmethod -->
</testsuite> <!-- Users -->
